### ISSUE TITLE
Handlebars fileTransform isn't working

### ISSUE THREAD

**Issue by s-oram** [bmatcuk/html-brunch-static#7]
I've set up a basic project using brunch and html-brunch-static to process handlebars templates. It seems to work fine when leaving everything with the default settings. ie, My handlebars templates are being read, converted and output in the correct location. 

The fileTransform option doesn't seem to have any impact however.

brunch-config.coffee
```
module.exports =
  files:
    javascripts: joinTo: 'app.js'
    stylesheets: joinTo: 'app.css'
    templates: joinTo: 'app.js'
  plugins:
    static:
      processors: [
        require('html-brunch-static')(
          handlebars:
            enableProcessor: true
            fileTransform: ( (f) -> f.replace(/\.static\.\w+$/, '.htmlxx') )
        )
      ]
```
With the above config I would expect 
`myfile.static.hbs` to become `myfile.htmlxx`.
but the actual result is
`myfile.static.hbs` becomes `myfile.html`.

Any idea what I'm doing wrong?
